# Generated by Django 6.0.5 on 2026-06-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_car_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Car",
            new_name="car",
        ),
    ]
